### ISSUE TITLE
ALL UP CHECKLIST

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/sommelier#22]
- [x] Goreli Graph node synced @tony-iqlusion 
  * [x] Test w/ oracle feeder @jackzampolin 
- [x] Logic contract for withdraws @zmanian 
- [ ] Encoding call for logic contract 
  * [ ] Go side (in the module) @jackzampolin [logic contract](https://github.com/althea-net/cosmos-gravity-bridge/blob/master/solidity/contracts/TestUniswapLiquidity.sol)
  * [x] Rust side (in the relayer) @jkilpatr 
- [x] Merge IL module PR (https://github.com/PeggyJV/sommelier/pull/14)
- [x] Batched txs for IL module
- [ ] Commit - reveal oracle phases
- [ ] Prunning oracle data and stoploss positions
- [ ] Deploy peggy contract @jkilpatr 
  * [ ] Need initial keys from testnet validators @jackzampolin @jkilpatr @zmanian @fedekunze @tony-iqlusion 
- [ ] Genesis file @jackzampolin @jkilpatr @zmanian @fedekunze @tony-iqlusion 
- [ ] Spin up network @jackzampolin @jkilpatr @zmanian @fedekunze @tony-iqlusion

**Comment by zmanian** [comment]
Added PR here for the missing graph node documentation here.
https://github.com/graphprotocol/graph-node/pull/2182
