### ISSUE TITLE
Mainnet Plan

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/sommelier#40]
The following is a list of components required for `sommelier` protocol. In order to properly test, we need these components in a full integration testing suite that allow for end to end local testing. Once this checklist is complete, public testnets will begin:

### Components
- [Cellar Contracts](https://github.com/VolumeFi/cellars)
  * [x] Finished Rebalance call
  * [x] Rebalance call ABI generated and committed to the allocation module repo w/ test https://github.com/PeggyJV/sommelier/issues/41
  * [x] npm install for contracts https://github.com/VolumeFi/cellars/issues/1
  * [x] test suite that includes uniswap v3 integration testing, see the [v3 staking contract tests](https://github.com/omarish/uniswap-v3-staker/tree/master/test) https://github.com/VolumeFi/cellars/issues/2
  * [x] Pay validators out of fees generated on cellars https://github.com/VolumeFi/cellars/issues/3
  * [ ] Gas optimization for rebalance call
- [Allocation Module](https://github.com/PeggyJV/sommelier/pull/39)
  * [ ] Integrate cellar contract ABI https://github.com/PeggyJV/sommelier/issues/41
  * [ ] Handle invalidation ID/ nonce and retries for timed out transactions (cc @jtremback) https://github.com/PeggyJV/sommelier/issues/42
  * [ ] finalize voting method (i.e. every period or when a number of votes accumulate during a period) https://github.com/PeggyJV/sommelier/issues/43
- Allocation feeder (TBD name, `aphid`?) https://github.com/PeggyJV/sommelier/issues/44
  * [ ] decide on language (JS, Go, Rust)
  * [ ] ingest data from APIs (TODO: which apis? just v2 and v3 graph?)
  * [ ] price range decision method (i.e. bollinger bands or other)
  * [ ] loop over list of contracts in allocation params 
  * [ ] send transactions when allocations should change
- [Gravity Bridge](https://github.com/peggyjv/gravity-bridge)
  * [x] Passing integration tests
  * [ ] Docker/binary/artifacts built in CI on each commit for consumption by downstream CI processes https://github.com/PeggyJV/gravity-bridge/issues/30
  * [ ] Finalize handling of contract call txs and how to time them out with additional testing and examples of invalidation id/nonce working in practice https://github.com/PeggyJV/gravity-bridge/issues/31

### Integrating all the components
- Sommelier Integration testing https://github.com/PeggyJV/sommelier/issues/45
  * [ ] Four validator sommelier chain w/ gravity and allocation modules wired up
  * [ ] Four orchestrators connected
  * [ ] Four allocation feeders connected
  * [ ] Mock/real graph data for testing (TODO: need to decide if we want to spin up full graph infra in integration environment)
  * [ ] Ethereum chain
  * [ ] Gravity contract deployed
  * [ ] Cellar contract deployed
  * [ ] Uni v3 deployed
  * [ ] testing erc20s and supporting infra deployed
  * [ ] Integration test spins up full environment, and tests adding/removing liquidity and rebalances
